#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGISTRY="$SCRIPT_DIR/registry.csv"
OUTPUT="$SCRIPT_DIR/MAP.md"

# Load config
# shellcheck source=.env
[[ -f "$SCRIPT_DIR/.env" ]] && source "$SCRIPT_DIR/.env"
GITHUB_USER="${GITHUB_USER:-}"
[[ -z "$GITHUB_USER" ]] && { echo "Error: GITHUB_USER not set. Copy .env.example to .env and fill it in."; exit 1; }

# Parse a CSV line handling quoted fields
parse_csv_line() {
    local line="$1"
    FIELDS=()
    local field=""
    local in_quotes=0

    while IFS= read -rn1 char; do
        if [[ "$in_quotes" -eq 1 ]]; then
            if [[ "$char" == '"' ]]; then
                in_quotes=0
            else
                field+="$char"
            fi
        else
            if [[ "$char" == '"' ]]; then
                in_quotes=1
            elif [[ "$char" == ',' ]]; then
                FIELDS+=("$field")
                field=""
            else
                field+="$char"
            fi
        fi
    done <<< "$line"
    FIELDS+=("$field")
}

# Sanitize repo name for Mermaid node ID
sanitize_id() {
    echo "$1" | tr '-' '_' | tr '.' '_' | sed 's/^[0-9]/_&/'
}

# --- Configuration ---

EXCLUDE_TAGS="personal dev"
EXCLUDE_PATTERN=$(echo "$EXCLUDE_TAGS" | tr ' ' '|')

# Repos that reference everything (index/meta repos) — skip as edge sources
SKIP_SOURCES="repo-registry ${GITHUB_USER}"

# --- Phase 1: Gather nodes (managed repos) ---

ALL_TAGS=""
REPO_NAMES=""
REPO_PATHS=""  # lines of "name:local_path"
REPO_TAGS=""   # lines of "name:tags"

while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    parse_csv_line "$line"
    managed="${FIELDS[8]:-}"
    [[ "$managed" != "yes" ]] && continue

    path="${FIELDS[1]:-}"
    tags="${FIELDS[6]:-}"
    name=$(basename "$path")

    REPO_NAMES+="$name"$'\n'
    REPO_PATHS+="$name:$HOME/$path"$'\n'
    REPO_TAGS+="$name:$tags"$'\n'

    if [[ -n "$tags" ]]; then
        IFS=';' read -ra tag_arr <<< "$tags"
        for tag in "${tag_arr[@]}"; do
            tag=$(echo "$tag" | xargs)
            ALL_TAGS+="$tag"$'\n'
        done
    fi
done < <(tail -n +2 "$REGISTRY")

SORTED_TAGS=$(echo "$ALL_TAGS" | sort -u | grep -v '^$' | grep -Ev "^(${EXCLUDE_PATTERN})$" || true)

# Build list of unique repo names for grepping
UNIQUE_NAMES=$(echo "$REPO_NAMES" | sort -u | grep -v '^$')

# --- Phase 2: Discover edges by scanning repos ---

echo "Scanning repos for cross-references..."

EDGES=""

while IFS= read -r entry; do
    [[ -z "$entry" ]] && continue
    source_name=$(echo "$entry" | cut -d':' -f1)
    source_path=$(echo "$entry" | cut -d':' -f2-)

    [[ ! -d "$source_path" ]] && continue

    # Skip index/meta repos that reference everything
    if echo "$SKIP_SOURCES" | grep -qw "$source_name" 2>/dev/null; then
        continue
    fi

    # Find all ${GITHUB_USER}/ references in files up to 2 levels deep
    # Skip .git dirs and binary files
    refs=$(find "$source_path" -maxdepth 2 -type f ! -path '*/.git/*' \
        -exec grep -lI "${GITHUB_USER}/" {} + 2>/dev/null \
        | xargs grep -oh "${GITHUB_USER}/[A-Za-z0-9_.-]*" 2>/dev/null \
        | sed "s|${GITHUB_USER}/||" \
        | sort -u || true)

    while IFS= read -r target_name; do
        [[ -z "$target_name" ]] && continue
        # Strip trailing .git if present
        target_name="${target_name%.git}"
        [[ "$target_name" == "$source_name" ]] && continue

        # Only add edge if target is a known repo
        if echo "$UNIQUE_NAMES" | grep -qx "$target_name" 2>/dev/null; then
            edge_key="${source_name},${target_name}"
            if ! echo "$EDGES" | grep -q "^${edge_key}$" 2>/dev/null; then
                EDGES+="${edge_key}"$'\n'
                echo "  $source_name --> $target_name"
            fi
        fi
    done <<< "$refs"
done <<< "$REPO_PATHS"

echo ""

# --- Phase 3: Group repos by primary tag ---

PRINTED=""

is_printed() {
    echo "$PRINTED" | grep -qx "$1" 2>/dev/null
}

mark_printed() {
    PRINTED+="$1"$'\n'
}

# --- Phase 4: Render Mermaid ---

{
    echo "# Repository Map"
    echo ""
    echo "*Auto-generated by repo-map.sh — regenerate with \`./repo-map.sh\`*"
    echo "*Edges discovered by scanning repos for \`${GITHUB_USER}/repo-name\` references.*"
    echo ""
    echo '```mermaid'
    echo "graph LR"

    # Subgraphs by tag
    while IFS= read -r tag; do
        [[ -z "$tag" ]] && continue

        group_nodes=""
        while IFS= read -r entry; do
            [[ -z "$entry" ]] && continue
            name=$(echo "$entry" | cut -d':' -f1)
            tags=$(echo "$entry" | cut -d':' -f2-)

            has_tag=0
            if [[ -n "$tags" ]]; then
                IFS=';' read -ra tag_arr <<< "$tags"
                for t in "${tag_arr[@]}"; do
                    t=$(echo "$t" | xargs)
                    [[ "$t" == "$tag" ]] && has_tag=1
                done
            fi
            [[ "$has_tag" -eq 0 ]] && continue

            if ! is_printed "$name"; then
                sid=$(sanitize_id "$name")
                if [[ "$sid" != "$name" ]]; then
                    group_nodes+="        ${sid}[\"${name}\"]"$'\n'
                else
                    group_nodes+="        ${sid}"$'\n'
                fi
                mark_printed "$name"
            fi
        done <<< "$REPO_TAGS"

        if [[ -n "$group_nodes" ]]; then
            echo "    subgraph ${tag}"
            echo -n "$group_nodes"
            echo "    end"
        fi
    done <<< "$SORTED_TAGS"

    # Untagged repos
    orphan_nodes=""
    while IFS= read -r entry; do
        [[ -z "$entry" ]] && continue
        name=$(echo "$entry" | cut -d':' -f1)
        if ! is_printed "$name"; then
            sid=$(sanitize_id "$name")
            if [[ "$sid" != "$name" ]]; then
                orphan_nodes+="        ${sid}[\"${name}\"]"$'\n'
            else
                orphan_nodes+="        ${sid}"$'\n'
            fi
            mark_printed "$name"
        fi
    done <<< "$REPO_TAGS"

    if [[ -n "$orphan_nodes" ]]; then
        echo "    subgraph untagged"
        echo -n "$orphan_nodes"
        echo "    end"
    fi

    # Edges
    echo ""
    while IFS= read -r edge; do
        [[ -z "$edge" ]] && continue
        source=$(echo "$edge" | cut -d',' -f1)
        target=$(echo "$edge" | cut -d',' -f2)

        src_id=$(sanitize_id "$source")
        tgt_id=$(sanitize_id "$target")

        echo "    ${src_id} --> ${tgt_id}"
    done <<< "$EDGES"

    echo '```'
} > "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT" | xargs) lines)"
