#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REGISTRY="$SCRIPT_DIR/registry.csv"
ECOSYSTEM="$SCRIPT_DIR/ecosystem.md"
OUTPUT="$SCRIPT_DIR/CONTEXT.md"

# Parse a CSV line handling quoted fields (for descriptions with commas)
parse_csv_line() {
    local line="$1"
    FIELDS=()
    local field=""
    local in_quotes=0

    while IFS= read -rn1 char; do
        if [[ "$in_quotes" -eq 1 ]]; then
            if [[ "$char" == '"' ]]; then
                in_quotes=0
            else
                field+="$char"
            fi
        else
            if [[ "$char" == '"' ]]; then
                in_quotes=1
            elif [[ "$char" == ',' ]]; then
                FIELDS+=("$field")
                field=""
            else
                field+="$char"
            fi
        fi
    done <<< "$line"
    FIELDS+=("$field")
}

format_repo() {
    local line="$1"
    parse_csv_line "$line"

    local path="${FIELDS[1]:-}"
    local status="${FIELDS[2]:-}"
    local visibility="${FIELDS[3]:-}"
    local k3s="${FIELDS[4]:-}"
    local description="${FIELDS[5]:-}"
    local tags="${FIELDS[6]:-}"
    local name
    name=$(basename "$path")

    echo "### $name"
    if [[ -n "$description" ]]; then
        echo "$description"
    fi
    echo ""

    local meta="**Status**: $status | **Visibility**: $visibility"
    if [[ -n "$k3s" ]]; then
        meta+=" | **K3s deployed**: $k3s"
    fi
    if [[ -n "$tags" ]]; then
        meta+=" | **Tags**: ${tags//;/, }"
    fi
    echo "$meta"
    echo "**Path**: ~/$path"
    echo ""
}

# --- Main ---

if [[ ! -f "$ECOSYSTEM" ]]; then
    echo "Error: $ECOSYSTEM not found. Create it with your architecture notes." >&2
    exit 1
fi

# Tags to exclude from context (repos are still managed/synced, just not in CONTEXT.md)
EXCLUDE_TAGS="personal dev"

# Build list of unique tags from managed repos
ALL_TAGS=""

while IFS= read -r line; do
    parse_csv_line "$line"
    managed="${FIELDS[8]:-}"
    [[ "$managed" != "yes" ]] && continue

    tags="${FIELDS[6]:-}"
    if [[ -n "$tags" ]]; then
        IFS=';' read -ra tag_arr <<< "$tags"
        for tag in "${tag_arr[@]}"; do
            tag=$(echo "$tag" | xargs)
            ALL_TAGS+="$tag"$'\n'
        done
    fi
done < <(tail -n +2 "$REGISTRY")

# Get sorted unique tags, excluding personal/dev
EXCLUDE_PATTERN=$(echo "$EXCLUDE_TAGS" | tr ' ' '|')
SORTED_TAGS=$(echo "$ALL_TAGS" | sort -u | grep -v '^$' | grep -Ev "^(${EXCLUDE_PATTERN})$" || true)

# Track printed repos (newline-separated list of names)
PRINTED=""

is_printed() {
    echo "$PRINTED" | grep -qx "$1" 2>/dev/null
}

mark_printed() {
    PRINTED+="$1"$'\n'
}

{
    echo "# Project Ecosystem Context"
    echo ""
    echo "*Auto-generated by repo-context.sh — regenerate with \`./repo-context.sh\`*"
    echo "*Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*"
    echo ""
    echo "---"
    echo ""

    cat "$ECOSYSTEM"
    echo ""
    echo "---"
    echo ""
    echo "# Managed Repositories"
    echo ""

    # Print repos grouped by tag
    while IFS= read -r tag; do
        [[ -z "$tag" ]] && continue

        # Collect repos for this tag group
        group_content=""
        while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            parse_csv_line "$line"
            tags="${FIELDS[6]:-}"
            managed="${FIELDS[8]:-}"
            [[ "$managed" != "yes" ]] && continue

            # Check if this repo has the current tag
            has_tag=0
            if [[ -n "$tags" ]]; then
                IFS=';' read -ra tag_arr <<< "$tags"
                for t in "${tag_arr[@]}"; do
                    t=$(echo "$t" | xargs)
                    [[ "$t" == "$tag" ]] && has_tag=1
                done
            fi
            [[ "$has_tag" -eq 0 ]] && continue

            name=$(basename "${FIELDS[1]:-}")
            if ! is_printed "$name"; then
                group_content+="$(format_repo "$line")"$'\n'
                mark_printed "$name"
            fi
        done < <(tail -n +2 "$REGISTRY")

        # Only print header if group has content
        if [[ -n "$group_content" ]]; then
            echo "## $tag"
            echo ""
            echo "$group_content"
        fi
    done <<< "$SORTED_TAGS"

    # Print untagged managed repos
    has_untagged=0
    while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        parse_csv_line "$line"
        managed="${FIELDS[8]:-}"
        tags="${FIELDS[6]:-}"
        [[ "$managed" != "yes" ]] && continue
        [[ -n "$tags" ]] && continue

        name=$(basename "${FIELDS[1]:-}")
        if ! is_printed "$name"; then
            if [[ "$has_untagged" -eq 0 ]]; then
                echo "## other"
                echo ""
                has_untagged=1
            fi
            format_repo "$line"
            mark_printed "$name"
        fi
    done < <(tail -n +2 "$REGISTRY")

    # Include the repository map if it exists
    if [[ -f "$SCRIPT_DIR/MAP.md" ]]; then
        echo ""
        echo "---"
        echo ""
        cat "$SCRIPT_DIR/MAP.md"
    fi

} > "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT" | xargs) lines)"
